### PR TITLE
Remove broadcast streaming from dropdown

### PR DESCRIPTION
**Pull request by billy-the-fish**
Hi Shuvo, 
    I have removed Broadcast Streaming from the dropdown, added extensions marketplace link to the dropdown and a new button on the product overview template to add an authentication button.  These changes are necessary for the docs that have just been pushed to main. 
   Hope I have not made any mistakes, Happy validating. 

   Iain

### CODE REVIEW

**Comment by Mr-spShuvo** [comment]
@billy-the-fish Please Resolve/Merge conflicts

**Comment by billy-the-fish** [comment]
Hi Shuvo, 
   I've pulled from main and set the submodules to read from main. Absolutely no idea why the build is failing. The error says:
   
   fatal: remote error: upload-pack: not our ref d76578ef748e3baaafd6c0902a8979863cc40a3c
   
   Which means nothing to me I'm afraid. 
   
      Iain

**Comment by Mr-spShuvo** [comment]
Still shows conflicts with main branch. 
Can you fix it? @billy-the-fish

**Review by Mr-spShuvo — APPROVED** [review]
LGTM

**Pull request merged**
